/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { Html } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';
import * as THREE from 'three';


export function Macbook(props) {
  const { nodes, materials } = useGLTF('/model-draco.gltf')

  const [ laptopClose ] = useState(()=>new Audio('./sounds/laptopclose.mp3'));
  const [ laptopType ] = useState(()=>new Audio('./sounds/laptoptyping.mp3'));

  // booleans
  let isPressed = useRef(false);
  let laptopOpening = useRef(false);
  let closed = useRef(false);
  let soundPlayed = useRef(false);

  const htmlElement = useRef();
  const laptopScreen = useRef();

  const turnOffScreen = () => {
    htmlElement.current.children[0].style.display = 'none';
  }

  const turnOnScreen = () => {
    if(htmlElement.current) {
      htmlElement.current.children[0].style.display = 'block';
    }
    
  }

  const handleScreenPress = () => {
    // turn off screen and change var to true to initiate the animation
    laptopClose.currentTime = 0;
    turnOffScreen();
    isPressed.current = true;

  }

  const handleOpening = () => {
    if(closed.current) {
      laptopOpening.current = true;
      
    }


  }

  const laptopTypeSound = () => {
    laptopType.currentTime = 0;
    laptopType.play();
  }


  useFrame((state)=>{
    // console.log(state.clock.getElapsedTime());

    // 1.311 is the value where the laptop is opened and we can return the visibility of the html page
    
    if(laptopScreen.current.rotation.x >= Math.PI) {
        // stop closing animation
        isPressed.current = false;
        closed.current = true;

        if(!soundPlayed.current) {
          soundPlayed.current = true;

          const a = laptopClose
          a.currentTime = 0.7;

          a.play().then(()=>{
            setTimeout(()=>a.pause(), 800);
          })
          .catch(err=>console.log("play error: ", err));
        }
    }

    if(laptopScreen.current.rotation.x <= 1.311) {
      if(!isPressed.current) {
        turnOnScreen();
      }
      // stop opening animation
      laptopOpening.current = false;
      closed.current = false;
      soundPlayed.current = false;
    }

    if(isPressed.current) {
      // do the animation to close the laptop
      laptopScreen.current.rotation.x += 0.05 * 0.09;
      console.log(laptopScreen.current.rotation.x);
    }

    if(laptopOpening.current) {
      // open laptop
      laptopScreen.current.rotation.x -= 0.05 * 0.09;
      console.log(laptopScreen.current.rotation.x);
    } 
  })

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.519, 0]} scale={0.103}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials['Frame.001']} // laptop part around the keyboard and mouse, the majority
          onClick={handleOpening}
          
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_1.geometry}
          material={materials['Frame.001']}
          
          
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_2.geometry}
          material={materials.HeadPhoneHole}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_3.geometry}
          material={materials.USB_C_INSIDE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_4.geometry}
          material={materials['Frame.001']}
          
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_5.geometry}
          material={materials.TouchbarBorder}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_6.geometry}
          material={materials.Keyboard}
        />
        <group position={[0, -0.509, 0]} scale={5.796}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle006.geometry}
            material={materials['Frame.001']} // touchpad
            
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle006_1.geometry}
            material={materials.USB_C_INSIDE}
          />
        </group>
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.FrontCameraRing001.geometry}
          material={materials['CameraRIngBlack.002']}
          position={[-0.155, 19.571, -16.151]}
          scale={5.796}
        /> */}
        <group position={[-11.786, -0.15, -8.301]} scale={5.796}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle.geometry}
            material={materials['Keyboard.001']}
            
            
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_1.geometry}
            material={materials.Key}
            
            
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_2.geometry}
            material={materials.Touchbar}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.KeyboardKeyHole.geometry}
          material={materials['Keyboard.001']}
          position={[-11.786, -0.152, -8.301]}
          scale={5.796}
          onClick={laptopTypeSound}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RubberFoot.geometry}
          material={materials.DarkRubber}
          position={[-11.951, -0.751, 7.857]}
          scale={5.796}
        />
        <group position={[0.011, -0.211, -10.559]} scale={5.796}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle012.geometry}
            material={materials.HingeBlack}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle012_1.geometry}
            material={materials.HingeMetal}
          />
        </group>
        <group position={[-15.026, 0.031, 0.604]} scale={5.796}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle009.geometry}
            material={materials['Frame.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle009_1.geometry}
            material={materials.SpeakerHole}
          />
        </group>
        <group position={[12.204, 0.031, 0.604]} scale={5.796}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle003.geometry}
            material={materials['Frame.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle003_1.geometry}
            material={materials.SpeakerHole}
          />
        </group>
        <group position={[0.007, -0.472, -10.412]} rotation={[1.311, 0, 0]} scale={5.796} ref={laptopScreen}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002.geometry}
            material={materials['Frame.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002_1.geometry}
            material={materials.Screen}
          >
            
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002_2.geometry}
            material={materials.ScreenGlass}
            // onPointerDown={handleScreenPress}
          >
            {/* Invisible hitbox INSIDE the screen */}
            <mesh
              onPointerDown={handleScreenPress}
              position={[0, 0.3, -3.4]} // small offset forward in LOCAL space
              scale={[5.1, 0.9, 0.1]}
              rotation={[1.5, 0, 0]}
              raycast={THREE.Mesh.raycast}
            >
              <boxGeometry />
              <meshBasicMaterial transparent opacity={0} />
            </mesh>
            <Html
                transform
                wrapperClass='htmlScreen'
                distanceFactor={1.95}
                // z in this case since it's html is diagonal
                position={[0, -0.05, -1.9]}
                rotation-x={-1.57}
                ref={htmlElement}
            >
                <iframe src="https://coderfaris.github.io/"/>
            </Html>
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002_3.geometry}
            material={materials.Rubber}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002_4.geometry}
            material={materials.DisplayGlass}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.AppleLogo000.geometry}
            material={materials['AppleLogo.004']}
            position={[0.005, -0.111, -1.795]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.579}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model-draco.gltf')